/**
 * Maxilius token pipeline.
 *
 * Consumes W3C DTCG-format JSON ($value/$type, {dot.path} references) and emits:
 *   dist/css/tokens.css      — CSS custom properties (light + dark themes)
 *   dist/js/tokens.mjs/.d.ts — resolved token objects + cssVar helper
 *   dist/json/tokens.json    — resolved values (machine-readable)
 *   dist/figma/variables.json — Figma Variables import payload
 *
 * Zero dependencies; the source format stays interchangeable with Style Dictionary.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, 'src');
const DIST = join(ROOT, 'dist');
const PREFIX = 'mx';

// ---------------------------------------------------------------- load

const loadDir = (dir) =>
  readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => JSON.parse(readFileSync(join(dir, f), 'utf8')))
    .reduce(deepMerge, {});

function deepMerge(a, b) {
  const out = { ...a };
  for (const [k, v] of Object.entries(b)) {
    out[k] =
      v && typeof v === 'object' && !Array.isArray(v) && a[k] && typeof a[k] === 'object'
        ? deepMerge(a[k], v)
        : v;
  }
  return out;
}

const primitives = loadDir(join(SRC, 'primitives'));
const light = JSON.parse(readFileSync(join(SRC, 'semantic/light.json'), 'utf8'));
const dark = JSON.parse(readFileSync(join(SRC, 'semantic/dark.json'), 'utf8'));

// ---------------------------------------------------------------- walk & resolve

const isToken = (node) => node && typeof node === 'object' && '$value' in node;

/** flatten to [{ path: ['color','blue','500'], value, type }] */
function flatten(tree, path = []) {
  if (isToken(tree)) return [{ path, value: tree.$value, type: tree.$type }];
  return Object.entries(tree).flatMap(([k, v]) => flatten(v, [...path, k]));
}

const REF = /^\{([^}]+)\}$/;

function lookup(tree, dotPath) {
  const node = dotPath.split('.').reduce((n, k) => n?.[k], tree);
  if (!isToken(node)) throw new Error(`Unresolved token reference: {${dotPath}}`);
  return node.$value;
}

/** resolve {a.b.c} references against the primitives tree (chains allowed) */
function resolve(value) {
  let v = value;
  for (let i = 0; i < 10; i++) {
    const m = typeof v === 'string' && v.match(REF);
    if (!m) return v;
    v = lookup(primitives, m[1]);
  }
  throw new Error(`Reference cycle at ${value}`);
}

const cssName = (path) => `--${PREFIX}-${path.join('-')}`;

const primitiveTokens = flatten(primitives);
const lightTokens = flatten(light);
const darkTokens = flatten(dark);

// ---------------------------------------------------------------- css

function cssDecl(t, { refs }) {
  const raw = t.value;
  const m = typeof raw === 'string' && raw.match(REF);
  const value = m && refs ? `var(${cssName(m[1].split('.'))})` : resolve(raw);
  return `  ${cssName(t.path)}: ${value};`;
}

const banner = `/**\n * Maxilius Design System — generated by @maxilius/tokens. Do not edit.\n */\n`;

const css = [
  banner,
  ':root {',
  '  color-scheme: light;',
  ...primitiveTokens.map((t) => cssDecl(t, { refs: false })),
  '',
  ...lightTokens.map((t) => cssDecl(t, { refs: true })),
  '}',
  '',
  `[data-theme='dark'] {`,
  '  color-scheme: dark;',
  ...darkTokens.map((t) => cssDecl(t, { refs: true })),
  '}',
  '',
  '@media (prefers-color-scheme: dark) {',
  `  :root:not([data-theme='light']) {`,
  '    color-scheme: dark;',
  ...darkTokens.map((t) => '  ' + cssDecl(t, { refs: true })),
  '  }',
  '}',
  '',
].join('\n');

// ---------------------------------------------------------------- js / json

function toResolvedTree(tokens) {
  const out = {};
  for (const t of tokens) {
    let node = out;
    for (const k of t.path.slice(0, -1)) node = node[k] ??= {};
    node[t.path.at(-1)] = resolve(t.value);
  }
  return out;
}

const resolved = {
  primitives: toResolvedTree(primitiveTokens),
  semantic: { light: toResolvedTree(lightTokens), dark: toResolvedTree(darkTokens) },
};

const js = `${banner}
export const tokens = ${JSON.stringify(resolved, null, 2)};

/** cssVar('action.primary.bg') -> 'var(--${PREFIX}-action-primary-bg)' */
export const cssVar = (path) => \`var(--${PREFIX}-\${path.split('.').join('-')})\`;
`;

const dts = `${banner}
export declare const tokens: {
  primitives: Record<string, any>;
  semantic: { light: Record<string, any>; dark: Record<string, any> };
};
export declare const cssVar: (path: string) => string;
`;

// ---------------------------------------------------------------- figma variables

const figmaType = (t) =>
  t.type === 'color' ? 'COLOR' : /^-?[\d.]+(px|rem|ms)?$/.test(String(resolve(t.value))) ? 'FLOAT' : 'STRING';

const figmaValue = (t) => {
  const v = String(resolve(t.value));
  if (figmaType(t) !== 'FLOAT') return v;
  const n = parseFloat(v);
  return v.endsWith('rem') ? n * 16 : n; // px
};

const figma = {
  collections: [
    {
      name: 'Maxilius / Primitives',
      modes: ['Value'],
      variables: primitiveTokens.map((t) => ({
        name: t.path.join('/'),
        type: figmaType(t),
        values: { Value: figmaValue(t) },
      })),
    },
    {
      name: 'Maxilius / Semantic',
      modes: ['Light', 'Dark'],
      variables: lightTokens.map((t, i) => ({
        name: t.path.join('/'),
        type: figmaType(t),
        alias: {
          Light: String(t.value).match(REF)?.[1] ?? null,
          Dark: String(darkTokens[i].value).match(REF)?.[1] ?? null,
        },
        values: { Light: figmaValue(t), Dark: figmaValue(darkTokens[i]) },
      })),
    },
  ],
};

// sanity: light/dark must define identical semantic paths
const lp = lightTokens.map((t) => t.path.join('.')).join();
const dp = darkTokens.map((t) => t.path.join('.')).join();
if (lp !== dp) throw new Error('semantic/light.json and semantic/dark.json paths diverge');

// ---------------------------------------------------------------- write

for (const d of ['css', 'js', 'json', 'figma']) mkdirSync(join(DIST, d), { recursive: true });
writeFileSync(join(DIST, 'css/tokens.css'), css);
writeFileSync(join(DIST, 'js/tokens.mjs'), js);
writeFileSync(join(DIST, 'js/tokens.d.ts'), dts);
writeFileSync(join(DIST, 'json/tokens.json'), JSON.stringify(resolved, null, 2) + '\n');
writeFileSync(join(DIST, 'figma/variables.json'), JSON.stringify(figma, null, 2) + '\n');

console.log(
  `✓ tokens built: ${primitiveTokens.length} primitives, ${lightTokens.length} semantic × 2 themes`,
);
